language: julia
os:
  - linux
julia:
  - 0.6
#  - nightly
notifications:
  email: false
git:
  depth: 99999999
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ExtraTrees"); Pkg.test("ExtraTrees"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  # - julia -e 'cd(Pkg.dir("ExtraTrees")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ExtraTrees")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
